# Generated by Django 5.0.1 on 2024-01-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bron',
            name='people',
        ),
        migrations.RemoveField(
            model_name='bron',
            name='time',
        ),
    ]
