# Generated by Django 5.0.1 on 2024-01-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_bron_people_remove_bron_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bron',
            old_name='data',
            new_name='date',
        ),
    ]
