# Generated by Django 5.0.1 on 2024-01-05 06:42

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='main_photo/', verbose_name='Главное фото')),
                ('experience', models.CharField(max_length=255, verbose_name='Опыт работы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('name1', models.CharField(max_length=255, verbose_name='Название')),
                ('mini_descriptions1', models.TextField(verbose_name='Короткое описание')),
                ('name2', models.CharField(max_length=255, verbose_name='Название')),
                ('mini_descriptions2', models.TextField(verbose_name='Короткое описание')),
                ('name3', models.CharField(max_length=255, verbose_name='Название')),
                ('mini_descriptions3', models.TextField(verbose_name='Короткое описание')),
                ('name4', models.CharField(max_length=255, verbose_name='Название')),
                ('mini_descriptions4', models.TextField(verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.AlterField(
            model_name='slide',
            name='shef',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='shef_image/', verbose_name='Фото Шефа'),
        ),
    ]
