# Generated by Django 5.0.1 on 2024-01-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0005_categories_category_delete_dessert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
