# Generated by Django 5.0.1 on 2024-01-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0006_alter_categories_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Menu',
        ),
    ]
