# Generated by Django 5.0.1 on 2024-01-05 09:55

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0008_discount_alter_category_options_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Отзывы клиента',
                'verbose_name_plural': 'Отзывы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientsInline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('profation', models.CharField(max_length=255, verbose_name='Профессия')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('place_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients_words', to='secondary.clients')),
            ],
            options={
                'unique_together': {('place_info', 'name')},
            },
        ),
    ]
