# Generated by Django 5.0.1 on 2024-01-05 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0009_clients_clientsinline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='descriptions',
            new_name='descriptions1',
        ),
        migrations.RenameField(
            model_name='clientsinline',
            old_name='descriptions',
            new_name='descriptions2',
        ),
    ]
