# Generated by Django 5.0.1 on 2024-01-05 10:05

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0010_rename_descriptions_clients_descriptions1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsinline',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image/', verbose_name='Фотография'),
        ),
    ]
