# Generated by Django 5.0.1 on 2024-01-05 12:46

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_allfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='imagelast/', verbose_name='Фотография1')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='imagelast/', verbose_name='Фотография2')),
                ('title1', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title2', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=255, verbose_name='Локация')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('contacts', ckeditor.fields.RichTextField(verbose_name='Контакты')),
            ],
            options={
                'verbose_name': 'Надавний пост',
                'verbose_name_plural': 'Недавние посты',
            },
        ),
    ]
