# Generated by Django 5.0.1 on 2024-01-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0014_lastpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastpost',
            name='instagram',
            field=models.URLField(default=1, verbose_name='instagram URL'),
            preserve_default=False,
        ),
    ]
