# Generated by Django 5.0.1 on 2024-01-05 17:21

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0017_slideabout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Menu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='bakery_image/', verbose_name='Фото изделий')),
                ('title', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('price_now', models.CharField(max_length=255, verbose_name='Цена сейчас')),
                ('price_before', models.CharField(max_length=255, verbose_name='Цена раньше')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary.category2', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Меню2',
                'verbose_name_plural': 'Меню2',
            },
        ),
    ]
