# Generated by Django 5.0.1 on 2024-01-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0018_category2_menu2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category2',
            options={'verbose_name': 'Категория2', 'verbose_name_plural': 'Категории2'},
        ),
    ]
