# Generated by Django 5.0.1 on 2024-01-06 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0019_alter_category2_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category2',
            new_name='BigCategory',
        ),
        migrations.AlterModelOptions(
            name='bigcategory',
            options={'verbose_name': '1) Главная категория', 'verbose_name_plural': '1) Главная категория'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '2) Дочерная категория', 'verbose_name_plural': '2) Дочерная категория'},
        ),
        migrations.RenameField(
            model_name='bigcategory',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='bi_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='secondary.bigcategory', verbose_name='Выбрать главную категорию'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Menu2',
        ),
    ]
