# Generated by Django 5.0.1 on 2024-01-06 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0020_rename_category2_bigcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '3) Меню', 'verbose_name_plural': '3) Меню'},
        ),
    ]
