# Generated by Django 5.0.1 on 2024-01-06 16:38

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0021_alter_menu_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='bakery_image/', verbose_name='Фото изделий')),
                ('title', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('price_now', models.CharField(max_length=255, verbose_name='Цена сейчас')),
                ('price_before', models.CharField(max_length=255, verbose_name='Цена раньше')),
            ],
            options={
                'verbose_name': 'Еда в магазине',
                'verbose_name_plural': 'Еда в магазине',
            },
        ),
    ]
