# Generated by Django 5.0.1 on 2024-01-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0022_shopfood'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfood',
            name='descriptions',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
