# Generated by Django 5.0.1 on 2024-01-07 15:07

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0023_shopfood_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='imagelast/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Последние Новости',
                'verbose_name_plural': 'Последние Новости',
            },
        ),
        migrations.RemoveField(
            model_name='lastpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lastpost',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='lastpost',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='lastpost',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='lastpost',
            name='title2',
        ),
    ]
