# Generated by Django 5.0.1 on 2024-01-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0026_menu_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descriptions',
            new_name='descriprions',
        ),
    ]
