# Generated by Django 5.0.1 on 2024-01-07 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0029_remove_category_slug_alter_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='descriprions',
            new_name='descriptions',
        ),
    ]
