# Generated by Django 5.0.1 on 2024-01-08 11:56

import ckeditor.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0030_rename_descriprions_menu_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comment',
            field=models.TextField(default=1, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='descriprions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image_news1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_news1/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_news2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='image_news2/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='news',
            name='letter',
            field=models.TextField(default=1, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='mini_descriprions',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='mini_news',
            field=models.CharField(default=1, max_length=255, verbose_name='Доп новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
