# Generated by Django 5.0.1 on 2024-01-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0031_news_comment_news_descriprions_news_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_news1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image_news2',
            new_name='image2',
        ),
    ]
