# Generated by Django 5.0.1 on 2024-01-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0032_rename_image_news1_news_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='news',
            name='email',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
    ]
