# Generated by Django 5.0.1 on 2024-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0034_rename_comment_review_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='news',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='news_comments', to='secondary.review'),
        ),
    ]
