# Generated by Django 5.0.1 on 2024-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0036_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopfood',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='menu', to='secondary.menu'),
        ),
    ]
