# Generated by Django 5.0.1 on 2024-01-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0038_remove_shopfood_cart_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
