# Generated by Django 5.0.1 on 2024-01-05 06:03

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='price/', verbose_name='Логотип')),
                ('instagram', models.URLField(verbose_name='instagram URL')),
                ('dribbble', models.URLField(verbose_name='dribbble URL')),
                ('twitter', models.URLField(verbose_name='twitter URL ')),
                ('youtube', models.URLField(verbose_name=' youtube URL')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
