# Generated by Django 5.0.1 on 2024-01-09 04:48

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_settings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='user_image/', verbose_name='Фото изделий'),
        ),
    ]
